[fonts]
size = 20
family = "Fira Code"
extras = [{ family = "Noto Sans CJK JP" }]

[colors]
background = "#000000"
foreground = "#eaeaea"
cursor = "#eaeaea"

black = "#000000"
blue = "#8e8e8e"
cyan = "#6d6d6d"
green = "#bfbfbf"
magenta = "#828282"
red = "#d54e53"
white = "#eaeaea"
yellow = "#cecece"

light-black = "#666666"
light-blue = "#a0a0a0"
light-cyan = "#7a7a7a"
light-green = "#e5e5e5"
light-magenta = "#939393"
light-red = "#ff3334"
light-white = "#ffffff"
light-yellow = "#dddddd"
