background="#000000"
text="#f8f8f2"
subtle="#808080"
warning-text="#e01b24"
text-special-one="#cea1c6"
text-special-two="#ffffff"
top-bar-background="#5e5c64"
top-bar-text="#f8f8f2"
status-bar-background="#77767b"
status-bar-text="#f8f8f2"
status-bar-view-background="#cea1c6"
status-bar-view-text="#f8f8f2"
list-selected-background="#f6f5f4"
list-selected-text="#000000"
list-selected-inactive-background="#9a9996"
list-selected-inactive-text="#000000"
controls-text="#f8f8f8"
controls-highlight="#ffffff"
autocomplete-background="#272822"
autocomplete-text="#f8f8f8"
autocomplete-selected-background="#cea1c6"
autocomplete-selected-text="#f8f8f8"
button-color-one="#cea1c6"
button-color-two="#272822"
timeline-name-background="#272822"
timeline-name-text="#808080"
command-text="#f8f8f2"
